### ISSUE TITLE
[EPIC: E001] Create Default Community Health Files

### ISSUE THREAD

**Issue by antonio-crispino** [antonio-crispino/.github#1]
# Epic: E001 <span id="e-epic">

Create some default community health files for my repositories to use.

## Table of Contents <span id="e-table-of-contents">

1. [Description :memo:](#e-description "A detailed description of the Epic. This includes the business need, the goals, and the relevant stakeholders.")
2. [Priority :exclamation:](#e-priority "The priority of the Story (MoSCoW method).")
3. [Epic Points (EP) :star:](#e-epic-points-ep "The estimated effort required to complete the Epic.")
4. [Requirements :clipboard:](#e-requirements "A list of the high-level requirements (functional and non-functional) that must be met for the Epic to be considered complete. These will translate to Stories and Tasks.")
   1. [Functional](#e-functional)
   2. [Non-Functional](#e-non-functional)
5. [Constraints :lock:](#e-constraints "The constraints of the Epic.")
   1. [Scope](#e-scope "The scope of the Epic. This defines what is and is not included in the Epic, encompassing any related initiatives, projects, or Epics.")
   2. [Timeline](#e-timeline "The estimated start and end dates (duration) of the Epic.")
   3. [Budget](#e-budget "The estimated budget for the Epic.")
   4. [Other Constraints](#e-other-constraints "A list of any other constraints that the Epic may have.")
6. [Assumptions :question:](#e-assumptions "A list of things that are assumed to be true in the planning and execution of the Epic.")
7. [Risks :warning:](#e-risks "A list of potential risks that may impact the completion of the Epic.")
8. [Dependencies :chains:](#e-dependencies "A list of dependencies required for the completion of the Epic.")
9. [Acceptance Criteria :heavy_check_mark:](#e-acceptance-criteria "A list of conditions that must be met for the Epic to be considered complete. This can use the Given-When-Then (GWT) format and other statement formats if appropriate.")
10. [Child Issues :link:](#e-child-issues "A list of child issues that will contribute to the completion of the Epic.")
    1. [Stories](#e-stories)
    2. [Tasks](#e-tasks)
11. [Resources :books:](#e-resources "A list of useful resources/links for the Epic.")
12. [Notes :pencil2:](#e-notes "A list of additional information about the Epic.")

## 1 - Description :memo: <span id="e-description">

> _A detailed description of the Epic. This includes the business need, the goals, and any relevant stakeholders._

All project repositories should have community health files to set standards and guidelines for contributors. Therefore, the goal of this Epic is to create some default community health files for all of my repositories to use. These will be used if the repository itself does not have its own community health files, since those would override the defaults. Since this repository is public, I will ensure that the files are universal and not necessarily tailored to my needs alone so that others can use them (while respecting the [LICENSE](https://github.com/antonio-crispino/.github/blob/main/LICENSE)).

## 2 - Priority :exclamation: <span id="e-priority">

> _The priority of the Epic (MoSCoW method). Select one of the following priorities:_
>
> 1. :sunny: `must-have`
> 2. :large_orange_diamond: `should-have`
> 3. :large_blue_diamond: `could-have`
> 4. :no_entry: `won't-have`

`must-have`

## 3 - Epic Points (EP) :star: <span id="e-epic-points-ep">

> _The estimated effort required to complete the Epic. This is estimated using epic points (EP), which are based on and equivalent to user story points (USP). The number of epic points allocated represents the sum of the points (USP and TP) from all child issues._

The number of epic points is the sum of the points (USP and TP) from all child issues.

## 4 - Requirements :clipboard: <span id="e-requirements">

> _A list of the high-level requirements (functional and non-functional) that must be met for the Epic to be considered complete. These will translate to Stories and Tasks._

### Functional <span id="e-functional">

1. The project must be configured to automatically format, lint, and validate code during development in VS Code to maintain consistent coding standards.
2. There must be issue templates to facilitate contributors in raising specific types of issues. This will standardize the information included in specific issue types.
3. There must be a general pull request (PR) template to guide contributors when creating pull requests.
4. There must be a contributing file to document how contributors should contribute to the project. This includes branch, commit, and pull request conventions.
5. There must be a readme file that includes a detailed description of this repository.

### Non-Functional <span id="e-non-functional">

1. The formatting and linting should ensure a standardized and consistent codebase to promote readability and maintainability.
2. The issue and pull request templates should be clear and intuitive to use.
3. The contributing file and readme file (documentation) should be easy for users and contributors of varying technical backgrounds to understand.

## 5 - Constraints :lock: <span id="e-constraints">

> _The constraints of the Epic._

### Scope <span id="e-scope">

> _The scope of the Epic. This defines what is and is not included in the Epic, encompassing any related initiatives, projects, or Epics._

This Epic encompasses the creation of all default community health files.

### Timeline <span id="e-timeline">

> _The estimated start and end dates (duration) of the Epic._

This is based on the planned sprints (milestones) for the child issues (Stories and Tasks) linked to this Epic. The start date is the start date of the child issue with the earliest sprint, while the end date is the end date of the child issue with the latest sprint.

### Budget <span id="e-budget">

> _The estimated budget for the Epic._

US$ 0.00

### Other Constraints <span id="e-other-constraints">

> _A list of any other constraints that the Epic may have._

The constraints commonly associated with software development projects are implied. If any other constraints beyond what's ordinarily expected are identified, they will be stated here.

## 6 - Assumptions :question: <span id="e-assumptions">

> _A list of things that are assumed to be true in the planning and execution of the Epic._

The assumptions commonly associated with software development projects are implied. If any other assumptions beyond what's ordinarily expected are identified, they will be stated here.

1. The Visual Studio Code (VS Code) application is used for development.
2. All necessary VS Code extensions are installed and enabled.
3. The Git repository is hosted on [GitHub](https://github.com/).

## 7 - Risks :warning: <span id="e-risks">

> _A list of potential risks that may impact the completion of the Epic. Risk probability and risk impact range from 1 to 5, where 1 is "Very Low" and 5 is "Very High". Therefore, risk score (risk probability x risk impact) ranges from 1 to 25._

The risks commonly associated with software development projects are implied. If any other risks beyond what's ordinarily expected are identified, they will be stated here.

## 8 - Dependencies :chains: <span id="e-dependencies">

> _A list of dependencies required for the completion of the Epic._

1. **The Epic** depends on the completion of all of its child issues.

## 9 - Acceptance Criteria :heavy_check_mark: <span id="e-acceptance-criteria">

> _A list of conditions that must be met for the Epic to be considered complete. This can use the Given-When-Then (GWT) format and other statement formats if appropriate._

1. **Given** the VS Code editor is open, **when** a developer is programming, **then** the code is formatted, linted, and validated.
2. **Given** the GitHub website is open, **when** a contributor creates a new issue, **then** there are issue template options available.
3. **Given** an issue is complete, **when** a PR is made, **then** a PR template is present.
4. There is a contributing file.
5. There is a readme file.

## 10 - Child Issues :link: <span id="e-child-issues">

> _A list of child issues that will contribute to the completion of the Epic._

### Stories <span id="e-stories">

- [x] 1. [Story E001-S001](https://github.com/antonio-crispino/.github/issues/3 "Child Issue (Story)"): Create Markdown Issue and Pull Request Templates for Agile Project Management in Software Development
- [x] 2. [Story E001-S002](https://github.com/antonio-crispino/.github/issues/14 "Child Issue (Story)"): Convert the Markdown Issue Templates to Simplified YAML Issue Forms and Simplify the Pull Request Template

### Tasks <span id="e-tasks">

- [x] 1. [Task E001-T001](https://github.com/antonio-crispino/.github/issues/2 "Child Issue (Task)"): Project Setup
- [x] 2. [Task E001-T002](https://github.com/antonio-crispino/.github/issues/8 "Child Issue (Task)"): Create CONTRIBUTING File
- [x] 3. [Task E001-T003](https://github.com/antonio-crispino/.github/issues/9 "Child Issue (Task)"): Explain Project in README File

## 11 - Resources :books: <span id="e-resources">

> _A list of useful resources/links for the Epic._

1. [GitHub Default Community Health Files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

## 12 - Notes :pencil2: <span id="e-notes">

> _A list of additional information about the Epic._

None
