### ISSUE TITLE
[TASK: E001-T001] Project Setup

### ISSUE THREAD

**Issue by antonio-crispino** [antonio-crispino/.github#2]
# Task: [E001](https://github.com/antonio-crispino/.github/issues/1 "Parent Issue (Epic)")-T001 <span id="t-task">

The initial setup for the project which includes editor configuration, git configuration, code formatting, code linting, and schema validation.

## Table of Contents <span id="t-table-of-contents">

1. [Type :label:](#t-type "The type of Task.")
2. [Description :memo:](#t-description "A detailed description of the Task. This includes any relevant context, requirements, and constraints.")
3. [Priority :exclamation:](#t-priority "The priority of the Task (MoSCoW method).")
4. [Task Points (TP) :star:](#t-task-points-tp "The estimated effort required to complete the Task.")
5. [Dependencies :chains:](#t-dependencies "A list of dependencies required for the completion of the Task.")
6. [Acceptance Criteria :heavy_check_mark:](#t-acceptance-criteria "A list of conditions that must be met for the Task to be considered complete.")
7. [Subtasks :clipboard:](#t-subtasks "A list of subtasks required to complete the Task. These do not need to have their own Subtask issues, but they could.")
8. [Parent Issue (Epic) :link:](#t-parent-issue-epic "The parent issue (Epic) for this Task, if it has one.")
9. [Resources :books:](#t-resources "A list of useful resources/links for the Task.")
10. [Notes :pencil2:](#t-notes "A list of additional information about the Task.")

## 1 - Type :label: <span id="t-type">

> _The type of Task. Select one of the following types and add it as a label as well:_
>
> 1. :hammer_and_wrench: `build` (build): Changes that affect the build system or external dependencies.
> 2. :gear: `ci` (ci): Changes to CI configuration files and scripts.
> 3. :books: `documentation` (docs): Changes to documentation.
> 4. :rocket: `performance` (perf): Changes to code that improves performance.
> 5. :package: `refactor` (refactor): Changes to code that neither fixes a bug nor adds a feature.
> 6. :wastebasket: `revert` (revert): Changes that revert a previous commit.
> 7. :gem: `style` (style): Changes to code that do not affect its meaning (formatting, etc.).
> 8. :rotating_light: `test` (test): Changes to existing tests or adding missing tests.
> 9. _:recycle: `chore` (chore): Changes, additions, configurations, routines, or maintenance tasks that don't fit into any other category. Changes do not modify src or test files._

`chore`

## 2 - Description :memo: <span id="t-description">

> _A detailed description of the Task. This includes any relevant context, requirements, and constraints._

All projects should have a thorough initial setup and configuration to ensure high quality development. For this project, the initial setup for the project includes editor configuration (VS Code), git configuration, code formatting (Prettier), code linting (markdownlint & YAML by Red Hat), and schema validation (YAML by Red Hat & JSON by VS Code).

## 3 - Priority :exclamation: <span id="t-priority">

> _The priority of the Task (MoSCoW method). Select one of the following priorities:_
>
> 1. :sunny: `must-have`
> 2. :large_orange_diamond: `should-have`
> 3. :large_blue_diamond: `could-have`
> 4. :no_entry: `won't-have`

`must-have`

## 4 - Task Points (TP) :star: <span id="t-task-points-tp">

> _The estimated effort required to complete the Task. This is estimated using task points (TP), which are based on and equivalent to user story points (USP). The number of task points allocated is selected from the following Fibonacci-like sequence: [1, 2, 3, 5, 8, 13, 20, 40, 100]._

3 TP

## 5 - Dependencies :chains: <span id="t-dependencies">

> _A list of dependencies required for the completion of the Task._

None

## 6 - Acceptance Criteria :heavy_check_mark: <span id="t-acceptance-criteria">

> _A list of conditions that must be met for the Task to be considered complete._

1. The code is formatted for Markdown, YAML, and JSON.
2. The code is linted for Markdown and YAML.
3. The code is schema validated for YAML and JSON.
4. All project configurations override user configurations.

## 7 - Subtasks :clipboard: <span id="t-subtasks">

> _A list of subtasks required to complete the Task. These do not need to have their own Subtask issues, but they could._

- [x] 1. Configure VS Code workspace settings (`.vscode/settings.json`). Use best judgment when selecting which settings to use. Avoid settings that are simply for a user/collaborator's personal preference. Ensure that settings related to file structure, auto formatting, and auto fixing lint errors are set. Since workspace settings take precedence over VS Code user settings, ensure that the workspace settings are extensive even if they contain default values. This is to avoid conflicts with a collaborator's VS Code user settings. With regards to language specific user settings, these will override any non-language specific workspace settings. The workspace settings should not handle overriding language specific user settings with their default values. All workspace settings must adhere to all languages used in this project. Therefore, the collaborator must ensure that language specific user settings are not overriding any of the non-language specific workspace settings.
- [x] 2. Configure VS Code workspace "recommended" extensions (`.vscode/extensions.json`). Although these are "recommended", they should be enforced since they are necessary for the formatting, linting, and validating files in this project.
- [x] 3. Configure Git attributes (`.gitattributes`) to use LF (Line Feed) line endings.
- [x] 4. Configure the Prettier formatter. All formatting rules should be in the `.prettierrc.json` file, while the other settings should be in the workspace settings. Remember to also set defaults in workspace settings.Use the default rules and only modify them using best judgment. A `.prettierrc.json` file should be created with at least the default settings (in other words, empty) to override any user settings or parent folder with a `.prettierrc.json` file that a collaborator may have.
- [x] 5. Configure the markdownlint linter. All linting rules should be in the `.markdownlint.json` file, while the other settings should be in the workspace settings. Remember to also set defaults in workspace settings. Use the default rules and only modify them using best judgment. A `.markdownlint.json` file should be created with at least the default settings (in other words, empty) to override any user settings or parent folder with a `.markdownlint.json` file that a collaborator may have.
- [x] 6. Configure the YAML linter and validator in the workspace settings. Remember to also set defaults.
- [x] 7. Configure VS Code's built-in JSON validator in the workspace settings. Remember to also set defaults.

## 8 - Parent Issue (Epic) :link: <span id="t-parent-issue-epic">

> _The parent issue (Epic) for this Task, if it has one._

[Epic E001](https://github.com/antonio-crispino/.github/issues/1 "Parent Issue (Epic)"): Create Default Community Health Files

## 9 - Resources :books: <span id="t-resources">

> _A list of useful resources/links for the Task._

1. [VS Code Settings](https://code.visualstudio.com/docs/getstarted/settings)
2. [VS Code Workspace Recommended Extensions](https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions)
3. [Git Attributes](https://www.git-scm.com/docs/gitattributes)
4. [Prettier](https://prettier.io/) ([VS Code Extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode))
5. [markdownlint](https://github.com/DavidAnson/markdownlint#readme) ([VS Code Extension](https://marketplace.visualstudio.com/items?itemName=davidanson.vscode-markdownlint))
6. [YAML](https://github.com/redhat-developer/vscode-yaml#readme) ([VS Code Extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml))
7. [GitHub Markdown Preview](https://github.com/mjbvz/vscode-github-markdown-preview#readme) ([VS Code Extension](https://marketplace.visualstudio.com/items?itemName=bierner.github-markdown-preview))

## 10 - Notes :pencil2: <span id="t-notes">

> _A list of additional information about the Task._

None
